### ISSUE TITLE
Starting 0.10.0 fails with modal error

### ISSUE THREAD

**Issue by yafp** [yafp/media-dupes#130]
![20200608_ 210550](https://user-images.githubusercontent.com/67605/84070184-00333580-a9cc-11ea-80d9-677fcd5d4a17.png)
```
TypeError: $(...).modal is not a function
    at HTMLDocument.<anonymous> (file:///tmp/.mount_media-EVK9kY/resources/app/app/index.html:290:25)
    at mightThrow (/tmp/.mount_media-EVK9kY/resources/app/node_modules/jquery/dist/jquery.js:3762:29)
    at process (/tmp/.mount_media-EVK9kY/resources/app/node_modules/jquery/dist/jquery.js:3830:12)
    at sentryWrapped (/tmp/.mount_media-EVK9kY/resources/app/node_modules/@sentry/browser/dist/helpers.js:74:23)
```

---

media-dupes 0.10.0
Electron 9.0.2
linux 5.6.15-arch1-1
Locale: de

**Comment by yafp** [comment]
reason: somehow i managed to move both

* bootstrap
* animate.css

from dependencies to devdependencies

stupid me
