### ISSUE TITLE
certificate has expired - error while trying to update youtube-dl

### ISSUE THREAD

**Issue by yafp** [yafp/media-dupes#132]
![media_dupes_youtube-dl-update-error](https://user-images.githubusercontent.com/67605/84942149-b2f94700-b0e2-11ea-890c-2da7eb39eaee.png)
```
Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:223:5)
    at TLSSocket.EventEmitter.emit (domain.js:475:20)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)
```

---

media-dupes 0.10.20200617
Electron 9.0.4
linux 5.7.2-arch1-1
Locale: de

**Comment by awrog** [comment]
confirmed, it happens to me too.

**Comment by yafp** [comment]
@awrog 
thanks for the info. i am curious: 

* what media-dupes version
* youtube-dl version
* on which OS

are you running?

**Comment by yafp** [comment]
opened an issue in the related project: see https://github.com/przemyslawpluta/node-youtube-dl/issues/313

**Comment by yafp** [comment]
lets see if that still happens after updating to 0.10.2
