### ISSUE TITLE
TypeError: Expected `milliseconds` to be a positive number

### ISSUE THREAD

**Issue by yafp** [yafp/media-dupes#133]
```
TypeError: Expected `milliseconds` to be a positive number
    at /home/fidel/Dropbox/Temp/media-dupes/node_modules/p-timeout/index.js:14:9
    at new Promise (<anonymous>)
    at pTimeout (/home/fidel/Dropbox/Temp/media-dupes/node_modules/p-timeout/index.js:12:55)
    at /home/fidel/Dropbox/Temp/media-dupes/node_modules/metascraper-media-provider/src/get-media/provider/generic.js:63:12
    at /home/fidel/Dropbox/Temp/media-dupes/node_modules/metascraper-media-provider/src/get-media/index.js:13:42
    at memoized (/home/fidel/Dropbox/Temp/media-dupes/node_modules/memoize-one/dist/memoize-one.cjs.js:29:31)
    at author (/home/fidel/Dropbox/Temp/media-dupes/node_modules/metascraper-media-provider/src/index.js:108:48)
    at getValue (/home/fidel/Dropbox/Temp/media-dupes/node_modules/metascraper/src/get-data.js:18:21)
    at /home/fidel/Dropbox/Temp/media-dupes/node_modules/metascraper/src/get-data.js:30:27
    at arrayMap (/home/fidel/Dropbox/Temp/media-dupes/node_modules/lodash/lodash.js:639:23)
    at map (/home/fidel/Dropbox/Temp/media-dupes/node_modules/lodash/lodash.js:9554:14)
    at getData (/home/fidel/Dropbox/Temp/media-dupes/node_modules/metascraper/src/get-data.js:29:5)
    at /home/fidel/Dropbox/Temp/media-dupes/node_modules/metascraper/src/index.js:22:12
    at /home/fidel/Dropbox/Temp/media-dupes/app/js/modules/ui.js:1138:32
```

---

media-dupes 0.10.20200617
Electron 9.0.4
linux 5.7.2-arch1-1
Locale: de

**Comment by yafp** [comment]
opened an issue in metascraper - see https://github.com/microlinkhq/metascraper/issues/280
