### ISSUE TITLE
Certificate error downloaden Youtube-dl

### ISSUE THREAD

**Issue by awrog** [yafp/media-dupes#134]
Using Win 10 Pro
Version  10.0.18363

```
Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket.EventEmitter.emit (domain.js:476:20)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)
```

---

media-dupes 0.9.0
Electron 8.2.5
win32 10.0.18363
Locale: en-US

**Comment by awrog** [comment]
surpassed with same error version 10
