### ISSUE TITLE
error updating Youtube-dl

### ISSUE THREAD

**Issue by awrog** [yafp/media-dupes#135]
```
Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:223:5)
    at TLSSocket.EventEmitter.emit (domain.js:475:20)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)
```

---

media-dupes 0.10.1 (the win64.zip version)
Electron 9.0.3
win32 10.0.18363
Locale: en-US

**Comment by yafp** [comment]
Hi awrog, 

i recently got this error as well - see #132.
I did open an issue in the related project and am now waiting for feedback.

**Comment by yafp** [comment]
see #132
