### ISSUE TITLE
Error after adding video

### ISSUE THREAD

**Issue by awrog** [yafp/media-dupes#136]
```
TypeError: Cannot destructure property 'normalizeArguments' of 'as_promise_1.PromisableRequest' as it is undefined.
    at Object.<anonymous> (C:\Program Files\MediaDupes\resources\app\node_modules\got\dist\source\create.js:21:9)
    at Object.<anonymous> (C:\Program Files\MediaDupes\resources\app\node_modules\got\dist\source\create.js:210:3)
    at Module._compile (C:\Program Files\MediaDupes\resources\app\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:738:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (C:\Program Files\MediaDupes\resources\app\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\Program Files\MediaDupes\resources\app\node_modules\got\dist\source\index.js:7:18)
    at Object.<anonymous> (C:\Program Files\MediaDupes\resources\app\node_modules\got\dist\source\index.js:124:3)
    at Module._compile (C:\Program Files\MediaDupes\resources\app\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:738:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (C:\Program Files\MediaDupes\resources\app\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at toDoListSingleUrlAdd (C:\Program Files\MediaDupes\resources\app\app\js\modules\ui.js:1137:17)
    at Object.windowMainAddUrl (C:\Program Files\MediaDupes\resources\app\app\js\modules\ui.js:697:17)
    at windowMainClickButtonAddUrl (file:///C:/Program%20Files/MediaDupes/resources/app/app/js/renderer.js:64:8)
    at HTMLButtonElement.onclick (file:///C:/Program%20Files/MediaDupes/resources/app/app/index.html:124:305)
```

---

media-dupes 0.10.1
Electron 9.0.3
win32 10.0.18363
Locale: en-US

**Comment by yafp** [comment]
Hey,

is that something which happens repeatingly? Or just using a specific url?

**Comment by awrog** [comment]
Yapf,
I start the program, it almost immediately asks to update the youtube downloader
I select update
presto error!

![error-media-dupes](https://user-images.githubusercontent.com/12153667/86258184-d16b4200-bbba-11ea-9835-52c313c065a9.gif)

**Comment by yafp** [comment]
isn't that again #132 ?
