### ISSUE TITLE
Error when downloading audio from a YouTube URL

### ISSUE THREAD

**Issue by userbyte** [yafp/media-dupes#138]
```
Error: Command failed with exit code 1: U:\Programs\media-dupes\resources\app\node_modules\youtube-dl\bin\youtube-dl.exe --embed-thumbnail --ignore-errors --format bestaudio --output U:\Downloads\Audio\%(track_number)s-%(artist)s-%(album)s-%(title)s-%(id)s.%(ext)s --restrict-filenames --continue --prefer-ffmpeg --ffmpeg-location U:\Programs\media-dupes\resources\app\node_modules\ffmpeg-static-electron\bin\win\x64\ffmpeg.exe --add-metadata --audio-format mp3 --extract-audio --audio-quality 0 --fixup detect_or_warn --encoding utf8 http://www.youtube.com/watch?v=X-KwYX2u8e4
    at makeError (U:\Programs\media-dupes\resources\app\node_modules\execa\lib\error.js:56:11)
    at handlePromise (U:\Programs\media-dupes\resources\app\node_modules\execa\index.js:114:26)
```

---

media-dupes 0.10.1
Electron 9.0.3
win32 10.0.18363
Locale: en-US

**Comment by userbyte** [comment]
I have solved the problem by installing "Microsoft Visual C++ 2010 Redistributable Package (x86)" which is a requirement for youtube-dl that I was missing. 

Apologies for opening an issue that I solved myself in 5 minutes.
