### ISSUE TITLE
URIError: URI malformed

### ISSUE THREAD

**Issue by yafp** [yafp/media-dupes#25]
The download fails after a while of processing ...

This happened with 0.1.0 already - true for 0.2.0 as well.

CLI output:
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
URIError: URI malformed
    at decodeURI (<anonymous>)
    at normalizeUrl (/opt/media-dupes/resources/app/node_modules/@sentry/electron/dist/main/normalize.js:16:12)
    at /opt/media-dupes/resources/app/node_modules/@sentry/electron/dist/main/normalize.js:61:34
    at Array.forEach (<anonymous>)
    at Object.normalizeEvent (/opt/media-dupes/resources/app/node_modules/@sentry/electron/dist/main/normalize.js:59:27)
    at MainClient.<anonymous> (/opt/media-dupes/resources/app/node_modules/@sentry/electron/dist/main/client.js:35:37)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/media-dupes/resources/app/node_modules/tslib/tslib.js:107:62)
```

**Comment by yafp** [comment]
output in renderer:

```
downloadContent ::: All download processes are now started
/opt/media-dupes/resources/app/node_modules/@sentry/utils/dist/instrument.js:104 downloadContent ::: Problems downloading url _https://www.zdf.de/serien/silent-witness/viertel-vor-drei-1-100.html with the following parameters: _--verbose,--format,best,--output,/home/fidel/Downloads/media-dupes/%(title)s-%(id)s.%(ext)s,--add-metadata,--ignore-errors_.
(anonymous) @ /opt/media-dupes/resources/app/node_modules/@sentry/utils/dist/instrument.js:104
(anonymous) @ renderer.js:712
done @ /opt/media-dupes/resources/app/node_modules/youtube-dl/lib/youtube-dl.js:24
processTicksAndRejections @ internal/process/task_queues.js:85
Promise.then (async)
(anonymous) @ /opt/media-dupes/resources/app/node_modules/execa/lib/promise.js:5
execa @ /opt/media-dupes/resources/app/node_modules/universalify/index.js:23
youtubeDl @ /opt/media-dupes/resources/app/node_modules/youtube-dl/lib/youtube-dl.js:23
call @ /opt/media-dupes/resources/app/node_modules/youtube-dl/lib/youtube-dl.js:152
exec @ /opt/media-dupes/resources/app/node_modules/youtube-dl/lib/youtube-dl.js:165
downloadContent @ renderer.js:709
onclick @ index.html:94
/opt/media-dupes/resources/app/node_modules/execa/lib/error.js:56 Uncaught (in promise) Error: Command failed with exit code 1: /opt/media-dupes/resources/app/node_modules/youtube-dl/bin/youtube-dl --verbose --format best --output /home/fidel/Downloads/media-dupes/%(title)s-%(id)s.%(ext)s --add-metadata --ignore-errors -- https://www.zdf.de/serien/silent-witness/viertel-vor-drei-1-100.html
    at makeError (/opt/media-dupes/resources/app/node_modules/execa/lib/error.js:56)
    at handlePromise (/opt/media-dupes/resources/app/node_modules/execa/index.js:114)
    at processTicksAndRejections (internal/process/task_queues.js:85)
makeError @ /opt/media-dupes/resources/app/node_modules/execa/lib/error.js:56
handlePromise @ /opt/media-dupes/resources/app/node_modules/execa/index.js:114
processTicksAndRejections @ internal/process/task_queues.js:85
Promise.then (async)
(anonymous) @ /opt/media-dupes/resources/app/node_modules/execa/lib/promise.js:5
execa @ /opt/media-dupes/resources/app/node_modules/universalify/index.js:23
youtubeDl @ /opt/media-dupes/resources/app/node_modules/youtube-dl/lib/youtube-dl.js:23
call @ /opt/media-dupes/resources/app/node_modules/youtube-dl/lib/youtube-dl.js:152
exec @ /opt/media-dupes/resources/app/node_modules/youtube-dl/lib/youtube-dl.js:165
downloadContent @ renderer.js:709
onclick @ index.html:94
```

**Comment by yafp** [comment]
produced with this URL: 

https://www.zdf.de/serien/silent-witness/viertel-vor-drei-1-100.html

**Comment by yafp** [comment]
The example url does not offer a video anymore ....

**Comment by yafp** [comment]
Opened an issue at sentry:

https://github.com/getsentry/sentry-electron/issues/201

Dev made a pull request to add a try/catch - see 

https://github.com/getsentry/sentry-electron/pull/202

**Comment by yafp** [comment]
Seems like sentry-electron added a try/catch block.
Let's wait when a new release comes up

**Comment by yafp** [comment]
... still waiting for a new sentry release.

**Comment by yafp** [comment]
sentry 1.2.0 was released today.
Lets hope this fixes out problem.
