### ISSUE TITLE
[Bug] Upgrading youtube-dl binary on linux/deb build 0.4.0 fails

### ISSUE THREAD

**Issue by yafp** [yafp/media-dupes#50]
On appstart media-dues finds a youtube-dl binary update.
This fails to be installed with the following output.

```
Error: EACCES: permission denied, open '/opt/media-dupes/resources/app/node_modules/youtube-dl/bin/details'
    at Object.openSync (fs.js:447:3)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.writeFileSync (fs.js:1206:35)
    at error (/opt/media-dupes/resources/app/node_modules/youtube-dl/lib/downloader.js:79:8)
    at Request.end (/opt/media-dupes/resources/app/node_modules/youtube-dl/lib/downloader.js:55:7)
    at Request.emit (events.js:208:15)
    at Request.EventEmitter.emit (domain.js:476:20)
    at IncomingMessage.<anonymous> (/opt/media-dupes/resources/app/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:291:20)
    at IncomingMessage.emit (events.js:208:15)
    at IncomingMessage.EventEmitter.emit (domain.js:476:20)
    at endReadableNT (_stream_readable.js:1168:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

I guess media-dupes wants to write the path of the custom youtube-dl binary to `node_modules/youtube-dl/bin/details` which fails because of missing file permissions.

This might be specific to some builds - but not all. Most likely all linux builds, the mac os and the win installer....

---

media-dupes 0.4.0
Electron 7.1.9
linux 4.15.0-74-generic
Locale: de

**Comment by yafp** [comment]
it might make sense to check if details file is writeable before trying to run the update.

This would as well make #51 no longer needed.
