### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by hitman05** [yafp/media-dupes#99]
```
Error: EPERM: operation not permitted, open 'C:\Program Files\media-dupes\resources\app\node_modules\youtube-dl\bin\details'
    at Object.openSync (fs.js:440:3)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.writeFileSync (fs.js:1265:35)
    at error (C:\Program Files\media-dupes\resources\app\node_modules\youtube-dl\lib\downloader.js:79:8)
    at Request.end (C:\Program Files\media-dupes\resources\app\node_modules\youtube-dl\lib\downloader.js:55:7)
    at Request.emit (events.js:215:7)
    at Request.EventEmitter.emit (domain.js:476:20)
    at IncomingMessage.<anonymous> (C:\Program Files\media-dupes\resources\app\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at IncomingMessage.EventEmitter.emit (domain.js:476:20)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

---

media-dupes 0.6.0
Electron 8.1.0
win32 10.0.19041
Locale: en-US

**Comment by yafp** [comment]
gonna work on #98 and close this as duplicate
